# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# pool:
#  name: image
#  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build_stage
    displayName: Build Step
    jobs:
      - job: webApp
        displayName: Build WebAPP
        pool:
          name: Hosted Windows 2019 with VS2019 
          vmImage: windows-2019 

        variables:
          buildConfiguration: 'Release'

        steps:
           - task: DotNetCoreCLI@2
             inputs:
               command: 'restore'
               projects: '**/pipelines-dotnet-core.csproj'

           - task: DotNetCoreCLI@2
             inputs:
              command: 'build'
              projects: '**/pipelines-dotnet-core.csproj'
              arguments: '--configuration $(BuildConfiguration)'
           - task: DotNetCoreCLI@2
             inputs:
               command: 'publish'
               publishWebProjects: true
               arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/webapp'
           
           - task: PublishBuildArtifacts@1
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)/webapp'
               ArtifactName: 'drop'
               publishLocation: 'Container'

  - stage: Deploy_stage
    displayName: Deploy Stage
    dependsOn: Build_stage
    jobs:
      - deployment: DeployWebApp
        displayName: DeployWebAPP
        pool:
          name: Hosted Windows 2019 with VS2019 
          vmImage: windows-2019
        environment: devenv
        strategy:
         runOnce:
           deploy:
             steps:
               - script: echo my first deployment
              
        
         
        

